"""Add AI score breakdown to resume matches

Revision ID: 01eb749a9cfa
Revises: 706d79bbb74c
Create Date: 2025-11-22 13:33:24.797575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01eb749a9cfa'
down_revision = '706d79bbb74c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_score_breakdown', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_matches', schema=None) as batch_op:
        batch_op.drop_column('ai_score_breakdown')

    # ### end Alembic commands ###
