"""Add skill_weights to job_descriptions

Revision ID: 8b6f12e66e40
Revises: 01eb749a9cfa
Create Date: 2025-11-23 05:54:50.217754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b6f12e66e40'
down_revision = '01eb749a9cfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_descriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skill_weights', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_descriptions', schema=None) as batch_op:
        batch_op.drop_column('skill_weights')

    # ### end Alembic commands ###
